- hosts: localhost
  # remote_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
#     - role: openstack-volume-snapshot
    - role: openstack-ping

- hosts: COMP90024
  # remote_user: ubuntu
  # vars_files:
    # - host_vars/mrc.yaml
  roles:
    # - role: openstack-environment
    - role: openstack-ping