---

rmote_directory: /home/ubuntu



couchdb_working_directory: /home/ubuntu/couchdb

couchdb_name: couchdb_data
couchdb_image: couchdb:latest
couchdb_user: admin
couchdb_password: password
CouchDB_port: 5984
