# Common vars
availability_zone: melbourne-qh2-uom
network: qh2-uom-internal
project_directory: ~/Documents/GitHub/CCC_Team15/MRC
# Volume
volumes:
  - vol_name: manager-node-vol
    vol_size: 60
  - vol_name: slave-node-1-vol
    vol_size: 60
  - vol_name: slave-node-2-vol
    vol_size: 60
  # - vol_name: slave-node-3-vol
  #   vol_size: 60

# Security group
security_groups:
  - name: g15_ssh
    description: "security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: g15_http
    description: "security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: default_instance_security_group
    description: "default_instance_security_group"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  
# Instance
instances:
  - name: manager-node
    volumes: 'manager-node-vol'
  - name: slave-node-1
    volumes: 'slave-node-1-vol'
  - name: slave-node-2
    volumes: 'slave-node-2-vol'
  # - name: slave-node-3
  #   volumes: 'slave-node-3-vol'

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: ansible
instance_flavor: uom.mse.2c9g
