---

- name: Gather facts of remote host
  setup:
    gather_subset: all

- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python-pip

- name: Update pip
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: Install dependencies
  tags: always
  become: yes
  apt:
    name: ['xfsprogs', 'apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-dev', 'python3-setuptools','software-properties-common', 'unzip', 'vim']
    state: latest
    install_recommends: no
    update_cache: yes