---
- name: Call CouchDB API
  become: yes
  uri:
    url: http://{{ groups['managernode'][0] }}:{{couchdb_port}}/{{ cluster_setup }}
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\",\
             \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_password }}\", \"port\": \"{{couchdb_port}}\",\
             \"remote_node\": \"{{ item }}\", \"node_count\": \"{{ groups['COMP90024'] | length }}\",\
             \"remote_current_user\":\"{{ couchdb_user }}\", \"remote_current_password\":\"{{ couchdb_password }}\"}"
    headers:
      Content-Type: "application/json"
  loop: "{{ groups['workernodes'] }}"

- name: Tell other nodes to attach to the manager node
  become: yes
  uri:
    url: http://{{ groups['managernode'][0] }}:{{couchdb_port}}/{{ cluster_setup }}
    status_code: 201,409
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"add_node\", \"host\":\"{{ item }}\",\
             \"port\": \"{{ couchdb_port }}\", \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_password }}\"}"
    headers:
      Content-Type: "application/json"
  loop: "{{ groups['workernodes'] }}"

- name: Empty request to avoid an error message when finishing the cluster setup
  become: yes
  uri:
    url: http://{{ groups['managernode'][0] }}:{{couchdb_port}}/
    status_code: 200,201,409
    method: GET
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes

- name: Finish cluster configuration
  become: yes
  uri:
    url: http://{{ groups['managernode'][0] }}:{{ couchdb_port }}/{{ cluster_setup }}
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"finish_cluster\"}"
    headers:
      Content-Type: "application/json"