---
- name: Unistall old versions of docker
  tags: 'docker'
  become: yes
  apt: 
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent

- name: Install dependencies
  tags: 'docker'
  become: yes
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']

- name: Add Docker’s official GPG key
  tags: 'docker'
  become: yes
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up the stable repository
  tags: 'docker'
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  tags: 'install-docker'
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  tags: 'install-docker'
  become: yes
  pip:
    name: ['docker-compose']
    state: latest
