---
  
- hosts: COMP90024
  remote_user: ubuntu
  vars_files:
    - host_vars/mrc.yaml
    - host_vars/deploy.yaml
  roles:
    - role: openstack-addproxy
    - role: openstack-ping
    - role: install-dependency
    - role: install-docker
    - role: git-clone-repo
    - role: docker-mount-volumes