---
- name: Unistall old versions of docker
  tags: 'docker'
  become: yes
  apt: 
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent

- name: Update the apt package index and install packages to allow apt to use a repository over HTTPS
  tags: 'docker'
  become: yes
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']

- name: Add Docker’s official GPG key
  tags: 'docker'
  become: yes
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up the stable repository
  tags: 'docker'
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  tags: 'install-docker'
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  tags: 'install-docker'
  become: yes
  pip:
    name: ['docker-compose']
    state: latest

- name: Create directory
  tags: 'docker'
  become: yes
  file:
    path: "/etc/systemd/system/docker.service.d"
    recurse: yes
    state: directory

- name: create docker proxy file
  tags: 'docker'
  become: yes
  copy:
    content: "[Service]"
    dest: "/etc/systemd/system/docker.service.d/http-proxy.conf"

- name: Add proxy to docker service
  become: yes
  blockinfile:
    path: "/etc/systemd/system/docker.service.d/http-proxy.conf"
    block: |
      Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
      Environment="HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
      Environment="NO_PROXY=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
 
- name: Reload daemond
  become: yes
  command: systemctl daemon-reload

- name: Restart docker
  become: yes
  command: systemctl restart docker

- name: Connect to the Docker daemon socket
  become: yes
  command: chmod 666 /var/run/docker.sock